[build]
  command = "npm run notify-initializing && npm run build && npm run notify-building"

[[plugins]]
  package = "@netlify/plugin-run-functions"
  [plugins.inputs]
    functions = "functions"

[build.processing]
  command = "npm run notify-deploying"

[build.cleanup]
  command = "npm run notify-cleanup"

[build.post-processing]
  command = "npm run notify-post-processing"

[build.failed]
  command = "npm run notify-failure"