[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/auth-callback"
  to = "/netlify/functions/auth-callback"
  status = 200

[[redirects]]
  from = "/logout"
  to = "/netlify/functions/logout"
  status = 200