[build]
  command = "npm run notify-initializing && npm run build && npm run notify-building && npm run notify-deploying && npm run notify-cleanup && npm run notify-post-processing"

[build.processing]
  command = "npm run notify-deploying"

[build.cleanup]
  command = "npm run notify-cleanup"

[build.post-processing]
  command = "npm run notify-post-processing"

[build.failed]
  command = "npm run notify-failure"
